# Generated by Django 5.2.8 on 2025-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
