# Generated by Django 5.2.8 on 2025-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('success', 'Successful'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
