# Generated by Django 5.2.8 on 2025-12-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_teammember_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.ImageField(upload_to='trips/'),
        ),
    ]
