# Generated by Django 5.2.8 on 2025-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_sentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pay_later_deadline',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('approved', 'Approved by Admin'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
