# Generated by Django 6.0 on 2025-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_sentemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
